on: 
  push:
    branches:
      - main
name:  Deploy to production
jobs:
  web-deploy:
    name:  Deployed On Production Serve at ${{ github.event.head_commit.timestamp }}
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.arifhida.my.id
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
