name: Deploy to production

on:
  workflow_dispatch:  # <-- ini yang bikin bisa manual jalanin

jobs:
  web-deploy:
    name: Deployed On Production Server at ${{ github.event.head_commit.timestamp }}
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.arifhida.my.id
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
